set -g prefix C-a
unbind C-b

# Make C-a the prefix.
bind C-a send-prefix

# Shorten command delay.
set -sg escape-time 1

# Use C-a / to split window horizontally and C-a - to split vertically.
bind / split-window -h
bind - split-window -v

# Use Vi movement keys as pane movement keys.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# No status bar.
set -g status off

# Allow use of the mouse.
set -g mouse on

# Increase scollback.
set-option -g history-limit 5000

